name: Update GitHub Stats Cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Top Langs Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          # count_private=true is key here
          options: 'username=${{ github.repository_owner }}&layout=compact&count_private=true&theme=dark'
          path: profile/top-langs.svg
          token: ${{ secrets.STATS_TOKEN }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub stats" || exit 0
          git push
